import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static const String _languageKey = 'selected_language';
  static const String _defaultLanguage = 'English';

  static Future<String> getLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final language = prefs.getString(_languageKey) ?? _defaultLanguage;
      return language;
    } catch (e) {
      // Hapus data corrupt dan reset ke default
      try {
        final prefs = await SharedPreferences.getInstance();
        await prefs.remove(_languageKey);
      } catch (clearError) {
        // Silent error handling
      }
      return _defaultLanguage;
    }
  }

  static Future<void> setLanguage(String language) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language);
  }

  static String getLocalizedText(String key, String language) {
    switch (language) {
      case 'Indonesia':
        return _indonesianTexts[key] ?? key;
      case 'English':
      default:
        return _englishTexts[key] ?? key;
    }
  }

  static const Map<String, String> _englishTexts = {
    'home': 'Home',
    'autopost': 'Autopost',
    'plan': 'Plan',
    'more': 'More',
    'language': 'Language',
    'theme': 'Theme',
    'email': 'Email',
    'logout': 'Logout',
    'welcome': 'Welcome!',
    'login': 'Login',
    'register': 'Register',
    'forgot_password': 'Forgot Password',
    'verify_otp': 'Verify OTP',
    'reset_password': 'Reset Password',
    'send_otp': 'Send OTP',
    'verify': 'Verify',
    'resend_otp': 'Resend OTP',
    'account_verified': 'Account verified successfully!',
    'otp_verification_failed': 'OTP verification failed. Please try again.',
    'please_enter_complete_otp': 'Please enter the complete OTP.',
    'login_successful': 'Login successful!',
    'login_failed': 'Login failed. Please try again.',
    'registration_successful': 'Registration successful!',
    'password_reset_successful': 'Password reset successfully!',
    'passwords_do_not_match': 'Passwords do not match.',
    'please_enter_valid_email': 'Please enter a valid email',
    'password_must_be_at_least_6': 'Password must be at least 6 characters',
    'resending_otp': 'Resending OTP...',
    'password_reset_email_sent': 'Password reset email sent. Please check your inbox.',
    'otp_verified_successfully': 'OTP verified successfully!',
    'an_unexpected_error_occurred': 'An unexpected error occurred',
    'please_enter_a_valid_email': 'Please enter a valid email',
    'enter_your_email_to_receive': 'Enter your email to receive a password reset link.',
    'a_verification_code_has_been_sent': 'A verification code has been sent to',
    'log_in_to_your_account': 'Log in to your account to continue.',
    'enter_your_email_to_receive_otp': 'Enter your email to receive a verification code.',
    'manage_your_email_settings': 'Manage your email settings',
    'change_app_language': 'Change app language',
    'customize_app_appearance': 'Customize app appearance',
    'not_logged_in': 'Not logged in',
    'account': 'Account',
    'preferences': 'Preferences',
    'english': 'English',
    'indonesia': 'Indonesia',
    'bahasa_indonesia': 'Bahasa Indonesia',
    'coming_soon': 'Coming Soon!',
    'autopost_screen_coming_soon': 'Autopost Screen - Coming Soon!',
    'plan_screen_coming_soon': 'Plan Screen - Coming Soon!',
    'home_screen': 'Home Screen',
    'account_actions': 'Account Actions',
    'sign_out': 'Sign Out',
    'sign_out_description': 'Log out from your account',
    'sign_out_confirmation': 'Are you sure you want to sign out?',
    'cancel': 'Cancel',
    'error_signing_out': 'Error signing out',
    // Plan Screen
    'choose_your_plan': 'Choose Your Plan',
    'unlock_powerful_automation': 'Unlock powerful automation features',
    'current_status': 'Current Status',
    'max_configs': 'Max Configs',
    'days_left': 'Days Left',
    'total_sent': 'Total Sent',
    'max_configurations': 'Max Configurations',
    'days_duration': 'Days Duration',
    'support_247': '24/7 Support',
    'auto_sync': 'Auto Sync',
    'get_started': 'Get Started',
    'choose_plan': 'Choose Plan',
    'why_choose_our_plans': 'Why Choose Our Plans?',
    'automation': 'Automation',
    'automation_desc': 'Set up your posts once and let them run automatically',
    'analytics': 'Analytics',
    'analytics_desc': 'Track your posting performance and engagement',
    'scheduling': 'Scheduling',
    'scheduling_desc': 'Post at optimal times for maximum reach',
    'security': 'Security',
    'security_desc': 'Your data is protected with enterprise-grade security',
    'plan_purchased_successfully': 'Plan purchased successfully!',
    'purchase_failed': 'Purchase failed',
    'failed_to_load_plans': 'Failed to load plans',
    'recommended': 'RECOMMENDED',
    'payment_method': 'Payment Method',
    'plan_summary': 'Plan Summary',
    'select_payment_method': 'Select a Payment Method',
    'payment_methods': 'Payment Methods',
    'error_loading_payment_methods': 'Error loading payment methods.',
    'proceed': 'Proceed',
    'statistics': 'Statistics',
    'purchase_history': 'Purchase History',
    'no_purchase_history': 'No purchase history found',
    'purchase_history_will_appear': 'Your purchase history will appear here once you buy a plan',
    'total_purchases': 'Total Purchases',
    'total_spent': 'Total Spent',
    'completed': 'Completed',
    'pending': 'Pending',
    'filter': 'Filter',
    'all': 'All',
    'failed': 'Failed',
    'bank_transfer': 'Bank Transfer',
    'ewallet': 'E-Wallet',
    'qris': 'QRIS',
    'transfer_to': 'Transfer to',
    'pay_using': 'Pay using',
    'pay_with': 'Pay with',
    'scan_qr_code_to_pay': 'Scan QR code to pay',
    'payment_details': 'Payment Details',
    'transaction_id': 'Transaction ID',
    'enter_id_after_payment': 'Enter ID after payment',
    'notes': 'Notes',
    'additional_notes': 'Additional notes...',
    'claim_free_plan': 'Claim Free Plan',
    'complete_purchase': 'Complete Purchase',
    'purchase_successful': 'Purchase successful! Your plan will be activated soon.',
    'purchase_failed_try_again': 'Purchase failed. Please try again.',
    'copied_to_clipboard': 'Copied to clipboard',
    'could_not_launch_discord': 'Could not launch Discord. Please visit',
    'tooltip_purchase_history': 'Purchase History',
    'upload_payment_proof': 'Upload Payment Proof',
    'select_image': 'Select Image',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'upload_from': 'Upload from',
    'uploading': 'Uploading...',
    'upload_success': 'Upload successful!',
    'upload_failed': 'Upload failed',
    'invalid_image_file': 'Invalid image file format',
    'file_too_large': 'File size too large (max 32MB)',
    'payment_proof': 'Payment Proof',
    'upload_proof_optional': 'Upload proof of payment (optional)',
    'image_uploaded': 'Image uploaded successfully',
    'remove_image': 'Remove Image',
    'view_image': 'View Image',
    'free': 'FREE',
    // Banned Screen
    'account_suspended': 'Account Suspended',
    'account_suspended_desc': 'Your account has been suspended due to violation of our terms of service. Please contact support for more information.',
    'ban_details': 'Ban Details',
    'reason': 'Reason',
    'ban_duration': 'Ban Duration',
    'permanent': 'Permanent',
    'ban_expired': 'Ban has expired',
    'days_remaining': 'days remaining',
    'hours_remaining': 'hours remaining',
    'minutes_remaining': 'minutes remaining',
    'need_help': 'Need Help?',
    'contact_support': 'Contact Support',
    'contact_support_desc': 'If you believe this is a mistake, please contact our support team.',
    'support_contact_info': 'You can reach us through:',
    'join_discord_support': 'Join our Discord server for support:',
    'open_discord': 'Open Discord',
    'already_claimed': 'Already Claimed',
    'free_plan_claimed_once': 'Free plan can only be claimed once per user',
    'close': 'Close',
    'upload_proof_required': 'Upload proof of payment (required)',
    'select_payment_method_first': 'Please select a payment method first',
    'upload_payment_proof_first': 'Please upload payment proof first',
    // Missing UI texts
    'unsaved_changes': 'Unsaved Changes',
    'unsaved_changes_message': 'You have unsaved changes. Are you sure you want to leave?',
    'stay': 'Stay',
    'leave': 'Leave',
    'package_summary': 'Package Summary',
    'payment_method_selection': 'Payment Method Selection',
    'choose_payment_method': 'Choose Payment Method',
    'detail_pembayaran': 'Payment Details',
    'configs': 'Configs',
    'days': 'Days',
    // Autopost Screen
    'autopost_servers': 'AutoPost Servers',
    'choose_server_based_on_plan': 'Choose your server based on your subscription plan',
    'server_1': 'Server 1',
    'server_2': 'Server 2',
    'server_3': 'Server 3',
    'free_trial_access': 'Free Trial Access',
    'basic_plan_access': 'Basic Plan Access',
    'pro_plan_access': 'Pro Plan Access',
    'basic_autopost_features': 'Basic autopost features for trial users',
    'enhanced_features_basic': 'Enhanced features for basic plan subscribers',
    'premium_features_advanced': 'Premium features with advanced capabilities',
    'server_access_info': 'Server Access Info',
    'server_access_based_on_plan': 'Server access is based on your current subscription plan. Upgrade your plan to unlock more servers and features.',
    'access_requires_plan': 'Access to {server} requires {plan}',
    'under_development': 'Under Development',
    'server_coming_soon': 'Server {number} functionality is currently under development.\nWe\'re working hard to bring you the best experience!',
    'important_notice': 'Important Notice',
    'autopost_policy': 'AutoPost Policy',
    'plan_expiry_notice': 'When your plan expires:',
    'autopost_stopped': '• AutoPost will be stopped automatically',
    'config_deletion_warning': '• Configurations will be deleted after 30 days of non-renewal',
    'renew_plan_reminder': '• Please renew your plan to continue using AutoPost services',
    'contact_support_before_deletion': 'Contact support before 30 days to avoid losing your configurations',
    // Manage Token
    'manage_token': 'Manage Token',
    'universal_access': 'Universal Access',
    'manage_token_description': 'Manage your API tokens and autopost configurations',
    // Manage Token Screen
    'token_management': 'Token Management',
    'token_management_description': 'Configure your Discord bot token and autopost settings in one place',
    'max_1_configuration': 'Maximum 1 Configuration',
    'configuration': 'Configuration',
    'add_token': 'Add Token',
    'discord_token': 'Discord Token',
    'enter_discord_token': 'Enter your Discord bot token',
    'channel_id': 'Channel ID',
    'enter_channel_id': 'Enter Discord channel ID',
    'interval_minutes': 'Interval (Minutes)',
    'enter_interval': 'Enter posting interval',
    'minutes': 'minutes',
    'status': 'Status',
    'configuration_active': 'Configuration Active',
    'configuration_inactive': 'Configuration Inactive',
    'autopost_running_description': 'Your autopost is currently running and posting messages automatically',
    'autopost_paused_description': 'Your autopost is currently paused and not posting messages',
    'last_updated': 'Last Updated',
    'just_now': 'Just now',
    'save_configuration': 'Save Configuration',
    'update_configuration': 'Update Configuration',
    'delete_configuration': 'Delete Configuration',
    'information': 'Information',
    'how_to_get_token': 'How to Get Token',
    'token_guide_description': 'Go to Discord Developer Portal, create an application, then copy the bot token',
    'channel_id_info': 'Channel ID Info',
    'channel_id_guide_description': 'Right-click on Discord channel, select "Copy ID" (Developer Mode must be enabled)',
    'interval_info': 'Interval Info',
    'interval_guide_description': 'Set how often messages should be posted (minimum 5 minutes recommended)',
    'please_fill_all_fields': 'Please fill all fields',
    'configuration_saved_successfully': 'Configuration saved successfully',
    'confirm_deletion': 'Confirm Deletion',
    'delete_configuration_warning': 'Are you sure you want to delete this configuration? This action cannot be undone.',
    'delete': 'Delete',
    'configuration_deleted_successfully': 'Configuration deleted successfully',
    'configuration_activated': 'Configuration activated successfully',
    'configuration_deactivated': 'Configuration deactivated successfully',
    'please_enter_token': 'Please enter Discord token',
    'token_saved_successfully': 'Token saved successfully',
    'invalid_token': 'Invalid Discord token',
    'token_already_exists': 'This token already exists',
    'token_added_successfully': 'Token added successfully',
    'error_adding_token': 'Error adding token',
    'delete_token_warning': 'Are you sure you want to delete this token? This action cannot be undone.',
    'token_deleted_successfully': 'Token deleted successfully',
    'error_deleting_token': 'Error deleting token',
    'token_activated': 'Token activated successfully',
    'token_deactivated': 'Token deactivated successfully',
    'error_updating_token': 'Error updating token status',
    'validating_token': 'Validating token...',
    'no_tokens_found': 'No tokens found',
    'add_first_token': 'Add your first Discord bot token to get started',
    'your_tokens': 'Your Tokens',
    'active': 'Active',
    'inactive': 'Inactive',
    'valid': 'Valid',
    'invalid': 'Invalid',
    'check_validity': 'Check Validity',
    'token_valid': 'Token is valid',
    'token_invalid': 'Token is invalid',
    'error_checking_token': 'Error checking token validity',
  };

  static const Map<String, String> _indonesianTexts = {
    'home': 'Beranda',
    'autopost': 'Autopost',
    'plan': 'Paket',
    'more': 'Lainnya',
    'language': 'Bahasa',
    'theme': 'Tema',
    'email': 'Email',
    'logout': 'Keluar',
    'welcome': 'Selamat Datang!',
    'login': 'Masuk',
    'register': 'Daftar',
    'forgot_password': 'Lupa Password',
    'verify_otp': 'Verifikasi OTP',
    'reset_password': 'Reset Password',
    'send_otp': 'Kirim OTP',
    'verify': 'Verifikasi',
    'resend_otp': 'Kirim Ulang OTP',
    'account_verified': 'Akun berhasil diverifikasi!',
    'otp_verification_failed': 'Verifikasi OTP gagal. Silakan coba lagi.',
    'please_enter_complete_otp': 'Silakan masukkan OTP lengkap.',
    'login_successful': 'Login berhasil!',
    'login_failed': 'Login gagal. Silakan coba lagi.',
    'registration_successful': 'Pendaftaran berhasil!',
    'password_reset_successful': 'Password berhasil direset!',
    'passwords_do_not_match': 'Password tidak cocok.',
    'please_enter_valid_email': 'Silakan masukkan email yang valid',
    'password_must_be_at_least_6': 'Password minimal 6 karakter',
    'resending_otp': 'Mengirim ulang OTP...',
    'password_reset_email_sent': 'Email reset password telah dikirim. Silakan cek inbox Anda.',
    'otp_verified_successfully': 'OTP berhasil diverifikasi!',
    'an_unexpected_error_occurred': 'Terjadi kesalahan yang tidak terduga',
    'please_enter_a_valid_email': 'Silakan masukkan email yang valid',
    'enter_your_email_to_receive': 'Masukkan email Anda untuk menerima link reset password.',
    'a_verification_code_has_been_sent': 'Kode verifikasi telah dikirim ke',
    'log_in_to_your_account': 'Masuk ke akun Anda untuk melanjutkan.',
    'enter_your_email_to_receive_otp': 'Masukkan email Anda untuk menerima kode verifikasi.',
    'manage_your_email_settings': 'Kelola pengaturan email Anda',
    'change_app_language': 'Ubah bahasa aplikasi',
    'customize_app_appearance': 'Sesuaikan tampilan aplikasi',
    'not_logged_in': 'Belum masuk',
    'account': 'Akun',
    'preferences': 'Preferensi',
    'english': 'English',
    'indonesia': 'Indonesia',
    'bahasa_indonesia': 'Bahasa Indonesia',
    'coming_soon': 'Segera Hadir!',
    'autopost_screen_coming_soon': 'Halaman Autopost - Segera Hadir!',
    'plan_screen_coming_soon': 'Halaman Paket - Segera Hadir!',
    'home_screen': 'Halaman Beranda',
    'account_actions': 'Aksi Akun',
    'sign_out': 'Keluar',
    'sign_out_description': 'Keluar dari akun Anda',
    'sign_out_confirmation': 'Apakah Anda yakin ingin keluar?',
    'cancel': 'Batal',
    'error_signing_out': 'Gagal keluar',
    // Plan Screen
    'choose_your_plan': 'Pilih Paket Anda',
    'unlock_powerful_automation': 'Buka fitur otomasi yang powerful',
    'current_status': 'Status Saat Ini',
    'max_configs': 'Maks Konfigurasi',
    'days_left': 'Hari Tersisa',
    'total_sent': 'Total Terkirim',
    'max_configurations': 'Maksimal Konfigurasi',
    'days_duration': 'Durasi Hari',
    'support_247': 'Support 24/7',
    'auto_sync': 'Sinkronisasi Otomatis',
    'get_started': 'Mulai Sekarang',
    'choose_plan': 'Pilih Paket',
    'why_choose_our_plans': 'Mengapa Memilih Paket Kami?',
    'automation': 'Otomasi',
    'automation_desc': 'Atur postingan sekali dan biarkan berjalan secara otomatis',
    'analytics': 'Analitik',
    'analytics_desc': 'Lacak performa posting dan engagement Anda',
    'scheduling': 'Penjadwalan',
    'scheduling_desc': 'Posting di waktu optimal untuk jangkauan maksimal',
    'security': 'Keamanan',
    'security_desc': 'Data Anda dilindungi dengan keamanan tingkat enterprise',
    'plan_purchased_successfully': 'Paket berhasil dibeli!',
    'purchase_failed': 'Pembelian gagal',
    'failed_to_load_plans': 'Gagal memuat paket',
    'payment_method': 'Metode Pembayaran',
    'plan_summary': 'Ringkasan Paket',
    'select_payment_method': 'Pilih Metode Pembayaran',
    'payment_methods': 'Metode Pembayaran',
    'error_loading_payment_methods': 'Gagal memuat metode pembayaran.',
    'proceed': 'Lanjutkan',
    'statistics': 'Statistik',
    'purchase_history': 'Riwayat Pembelian',
    'no_purchase_history': 'Tidak ada riwayat pembelian ditemukan',
    'purchase_history_will_appear': 'Riwayat pembelian Anda akan muncul di sini setelah Anda membeli paket',
    'total_purchases': 'Total Pembelian',
    'total_spent': 'Total Pengeluaran',
    'completed': 'Selesai',
    'pending': 'Menunggu',
    'filter': 'Filter',
    'all': 'Semua',
    'failed': 'Gagal',
    'bank_transfer': 'Transfer Bank',
    'ewallet': 'E-Wallet',
    'qris': 'QRIS',
    'transfer_to': 'Transfer ke',
    'pay_using': 'Bayar menggunakan',
    'pay_with': 'Bayar dengan',
    'scan_qr_code_to_pay': 'Scan QR code untuk membayar',
    'payment_details': 'Detail Pembayaran',
    'transaction_id': 'ID Transaksi',
    'enter_id_after_payment': 'Masukkan ID setelah pembayaran',
    'notes': 'Catatan',
    'additional_notes': 'Catatan tambahan...',
    'claim_free_plan': 'Klaim Paket Gratis',
    'complete_purchase': 'Selesaikan Pembelian',
    'purchase_successful': 'Pembelian berhasil! Paket Anda akan diaktifkan segera.',
    'purchase_failed_try_again': 'Pembelian gagal. Silakan coba lagi.',
    'copied_to_clipboard': 'Disalin ke clipboard',
    'could_not_launch_discord': 'Tidak dapat membuka Discord. Silakan kunjungi',
    'tooltip_purchase_history': 'Riwayat Pembelian',
    'upload_payment_proof': 'Upload Bukti Pembayaran',
    'select_image': 'Pilih Gambar',
    'camera': 'Kamera',
    'gallery': 'Galeri',
    'upload_from': 'Upload dari',
    'uploading': 'Mengupload...',
    'upload_success': 'Upload berhasil!',
    'upload_failed': 'Upload gagal',
    'invalid_image_file': 'Format file gambar tidak valid',
    'file_too_large': 'Ukuran file terlalu besar (maks 32MB)',
    'payment_proof': 'Bukti Pembayaran',
    'upload_proof_optional': 'Upload bukti pembayaran (opsional)',
    'image_uploaded': 'Gambar berhasil diupload',
    'remove_image': 'Hapus Gambar',
    'view_image': 'Lihat Gambar',
    'recommended': 'DIREKOMENDASIKAN',
    'free': 'GRATIS',
    // Banned Screen
    'account_suspended': 'Akun Disuspend',
    'account_suspended_desc': 'Akun Anda telah disuspend karena melanggar ketentuan layanan kami. Silakan hubungi support untuk informasi lebih lanjut.',
    'ban_details': 'Detail Suspend',
    'reason': 'Alasan',
    'ban_duration': 'Durasi Suspend',
    'permanent': 'Permanen',
    'ban_expired': 'Suspend telah berakhir',
    'days_remaining': 'hari tersisa',
    'hours_remaining': 'jam tersisa',
    'minutes_remaining': 'menit tersisa',
    'need_help': 'Butuh Bantuan?',
    'contact_support': 'Hubungi Support',
    'contact_support_desc': 'Jika Anda merasa ini adalah kesalahan, silakan hubungi tim support kami.',
    'support_contact_info': 'Anda dapat menghubungi kami melalui:',
    'join_discord_support': 'Bergabung dengan server Discord kami untuk mendapatkan bantuan:',
    'open_discord': 'Buka Discord',
    'already_claimed': 'Sudah Diklaim',
    'free_plan_claimed_once': 'Paket gratis hanya bisa diklaim sekali per pengguna',
    'close': 'Tutup',
    'upload_proof_required': 'Upload bukti pembayaran (wajib)',
    'select_payment_method_first': 'Silakan pilih metode pembayaran terlebih dahulu',
    'upload_payment_proof_first': 'Silakan upload bukti pembayaran terlebih dahulu',
    // Missing UI texts
    'unsaved_changes': 'Perubahan Belum Disimpan',
    'unsaved_changes_message': 'Anda memiliki perubahan yang belum disimpan. Apakah Anda yakin ingin keluar?',
    'stay': 'Tetap',
    'leave': 'Keluar',
    'package_summary': 'Ringkasan Paket',
    'payment_method_selection': 'Pilihan Metode Pembayaran',
    'choose_payment_method': 'Pilih Metode Pembayaran',
    'detail_pembayaran': 'Detail Pembayaran',
    'configs': 'Konfigurasi',
    'days': 'Hari',
    // Autopost Screen
    'autopost_servers': 'Server AutoPost',
    'choose_server_based_on_plan': 'Pilih server berdasarkan paket langganan Anda',
    'server_1': 'Server 1',
    'server_2': 'Server 2',
    'server_3': 'Server 3',
    'free_trial_access': 'Akses Trial Gratis',
    'basic_plan_access': 'Akses Paket Basic',
    'pro_plan_access': 'Akses Paket Pro',
    'basic_autopost_features': 'Fitur autopost dasar untuk pengguna trial',
    'enhanced_features_basic': 'Fitur yang ditingkatkan untuk pelanggan paket basic',
    'premium_features_advanced': 'Fitur premium dengan kemampuan canggih',
    'server_access_info': 'Info Akses Server',
    'server_access_based_on_plan': 'Akses server didasarkan pada paket langganan Anda saat ini. Upgrade paket untuk membuka lebih banyak server dan fitur.',
    'access_requires_plan': 'Akses ke {server} memerlukan {plan}',
    'under_development': 'Sedang Dikembangkan',
    'server_coming_soon': 'Fungsionalitas Server {number} saat ini sedang dalam pengembangan.\nKami bekerja keras untuk memberikan pengalaman terbaik!',
    'important_notice': 'Pemberitahuan Penting',
    'autopost_policy': 'Kebijakan AutoPost',
    'plan_expiry_notice': 'Ketika paket Anda berakhir:',
    'autopost_stopped': '• AutoPost akan dihentikan secara otomatis',
    'config_deletion_warning': '• Konfigurasi akan dihapus setelah 30 hari tidak diperpanjang',
    'renew_plan_reminder': '• Harap perpanjang paket untuk melanjutkan layanan AutoPost',
    'contact_support_before_deletion': 'Hubungi support sebelum 30 hari untuk menghindari kehilangan konfigurasi',
    // Manage Token
    'manage_token': 'Kelola Token',
    'universal_access': 'Akses Universal',
    'manage_token_description': 'Kelola API token dan konfigurasi autopost Anda',
    // Manage Token Screen
    'token_management': 'Manajemen Token',
    'token_management_description': 'Konfigurasi Discord bot token dan pengaturan autopost dalam satu tempat',
    'max_1_configuration': 'Maksimal 1 Konfigurasi',
    'configuration': 'Konfigurasi',
    'add_token': 'Tambah Token',
    'discord_token': 'Discord Token',
    'enter_discord_token': 'Masukkan Discord bot token Anda',
    'channel_id': 'ID Channel',
    'enter_channel_id': 'Masukkan ID channel Discord',
    'interval_minutes': 'Interval (Menit)',
    'enter_interval': 'Masukkan interval posting',
    'minutes': 'menit',
    'status': 'Status',
    'configuration_active': 'Konfigurasi Aktif',
    'configuration_inactive': 'Konfigurasi Tidak Aktif',
    'autopost_running_description': 'Autopost Anda sedang berjalan dan memposting pesan secara otomatis',
    'autopost_paused_description': 'Autopost Anda sedang dijeda dan tidak memposting pesan',
    'last_updated': 'Terakhir Diperbarui',
    'just_now': 'Baru saja',
    'save_configuration': 'Simpan Konfigurasi',
    'update_configuration': 'Perbarui Konfigurasi',
    'delete_configuration': 'Hapus Konfigurasi',
    'information': 'Informasi',
    'how_to_get_token': 'Cara Mendapatkan Token',
    'token_guide_description': 'Buka Discord Developer Portal, buat aplikasi, lalu salin bot token',
    'channel_id_info': 'Info ID Channel',
    'channel_id_guide_description': 'Klik kanan pada channel Discord, pilih "Copy ID" (Developer Mode harus diaktifkan)',
    'interval_info': 'Info Interval',
    'interval_guide_description': 'Atur seberapa sering pesan harus diposting (minimum 5 menit disarankan)',
    'please_fill_all_fields': 'Harap isi semua kolom',
    'configuration_saved_successfully': 'Konfigurasi berhasil disimpan',
    'confirm_deletion': 'Konfirmasi Penghapusan',
    'delete_configuration_warning': 'Apakah Anda yakin ingin menghapus konfigurasi ini? Tindakan ini tidak dapat dibatalkan.',
    'delete': 'Hapus',
    'configuration_deleted_successfully': 'Konfigurasi berhasil dihapus',
    'configuration_activated': 'Konfigurasi berhasil diaktifkan',
    'configuration_deactivated': 'Konfigurasi berhasil dinonaktifkan',
    'please_enter_token': 'Harap masukkan Discord token',
    'token_saved_successfully': 'Token berhasil disimpan',
    'invalid_token': 'Discord token tidak valid',
    'token_already_exists': 'Token ini sudah ada',
    'token_added_successfully': 'Token berhasil ditambahkan',
    'error_adding_token': 'Gagal menambahkan token',
    'delete_token_warning': 'Apakah Anda yakin ingin menghapus token ini? Tindakan ini tidak dapat dibatalkan.',
    'token_deleted_successfully': 'Token berhasil dihapus',
    'error_deleting_token': 'Gagal menghapus token',
    'token_activated': 'Token berhasil diaktifkan',
    'token_deactivated': 'Token berhasil dinonaktifkan',
    'error_updating_token': 'Gagal mengubah status token',
    'validating_token': 'Memvalidasi token...',
    'no_tokens_found': 'Tidak ada token ditemukan',
    'add_first_token': 'Tambahkan Discord bot token pertama Anda untuk memulai',
    'your_tokens': 'Token Anda',
    'active': 'Aktif',
    'inactive': 'Tidak Aktif',
    'valid': 'Valid',
    'invalid': 'Tidak Valid',
    'check_validity': 'Periksa Validitas',
    'token_valid': 'Token valid',
    'token_invalid': 'Token tidak valid',
    'error_checking_token': 'Gagal memeriksa validitas token',
  };
} 